// Offline browser acceptance: every API is intercepted; no project files or model credits are used.
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'
import { appendStoryboard } from '../../web/src/workflowStudio.js'
import { emptyWorkflow, makeNode, makeShot } from '../../web/src/workflowGraph.js'
import { mentionToken } from '../../web/src/promptMentions.js'

const require = createRequire(new URL('../../web/package.json', import.meta.url))
const { chromium } = process.env.FRAMEFLOW_BROWSER_MODULES
  ? require(path.join(process.env.FRAMEFLOW_BROWSER_MODULES, 'playwright'))
  : require('playwright')
// A valid local clip tests playback/compare controls without using a generated model video.
// npm scripts run in web; fixtures and screenshots are resolved from the repository root.
process.chdir(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..'))
const videoFixture = execFileSync(process.env.PYTHON || 'python', ['-c', `import imageio_ffmpeg,subprocess,tempfile,pathlib,sys
with tempfile.TemporaryDirectory() as d:
 p=pathlib.Path(d)/'fixture.mp4'
 subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(),'-y','-v','error','-f','lavfi','-i','color=c=0x293646:s=320x180:r=24','-t','1','-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',str(p)],check=True)
 sys.stdout.buffer.write(p.read_bytes())`])
const browser = await chromium.launch({ ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}), headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } })
const page = await context.newPage()
const errors = [], unexpected = [], submissions = [], compositions = [], jobs = new Map()
page.on('pageerror', error => errors.push(error.message))
const taskId = '123456abcdef', url = process.env.E2E_URL || 'http://127.0.0.1:5173'
const cfg = { video_backend: 'comfyui', comfyui_url: 'http://mock-comfyui', video_workflow: 'i2v', text_api_key: 'mock-key', video_megapixels: '.5', audio_provider: 'edge' }
let graph = emptyWorkflow(), failNext = false, failCandidateIndex = null, heldJob = false, saveFailure = false, exportRequest, historicalRecords = []
const project = { title: '山海之间 · 创作练习', characters: [], assets: [{ kind: 'scene', name: '山海晨光', anchor: '山间薄雾，开阔远景，柔和自然光。', images: ['morning.webp'] }, { kind: 'prop', name: '未寄出的信', anchor: '故事里的一封旧信。', sheet: 'letter.webp', images: [] }] }
const task = { task_id: taskId, project, status: 'succeeded', shots: [], blocks: [], flow: 'blocks' }
await page.route('**/files/**', route => route.fulfill({ contentType: route.request().url().endsWith('.mp4') ? 'video/mp4' : 'image/webp', body: route.request().url().endsWith('.mp4') ? videoFixture : fs.readFileSync('web/public/images/inspiration-mountain.webp') }))
await page.route('**/api/**', async route => {
  const request = route.request(), pathname = new URL(request.url()).pathname, method = request.method()
  const json = data => route.fulfill({ contentType: 'application/json', body: JSON.stringify(data) })
  if (pathname === '/api/config') return json(cfg)
  if (pathname === '/api/video-capabilities') return json({ controls_version: 1, video_sources_version: 1 })
  if (pathname === '/api/tasks') return json([])
  if (pathname === '/api/tasks/draft') return json({ task_id: taskId })
  if (pathname.endsWith('/video-uploads') && method === 'POST') {
    assert.equal(request.headers()['content-type'], 'application/octet-stream')
    assert.ok(request.postDataBuffer().length > 0)
    return json({ id: 'uploaded-video', status: 'succeeded', origin: 'upload', file: 'upload_012345abcdef.mp4',
      url: `/files/${taskId}/video_uploads/upload_012345abcdef.mp4`, poster: `/files/${taskId}/video_uploads/upload_012345abcdef.jpg`,
      width: 320, height: 180, actual_duration: 1, original_filename: '参考视频.mp4' })
  }
  if (pathname === `/api/tasks/${taskId}`) return json(task)
  if (pathname.endsWith('/workflow')) {
    if (method === 'GET') return json(graph)
    if (saveFailure) return route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: '模拟保存失败' }) })
    const payload = request.postDataJSON()
    assert.equal(payload.revision, graph.revision)
    graph = structuredClone(payload); graph.revision++
    return json({ ok: true, revision: graph.revision })
  }
  if (pathname.endsWith('/segments')) return json({ items: historicalRecords })
  if (pathname.endsWith('/docs')) return json({ items: [] })
  if (pathname.endsWith('/history')) return json({ keep: 10, versions: [{ current: true, thumb: `/files/${taskId}/scene/morning.webp`, bytes: 100, files: ['morning.webp'] }] })
  if (pathname.includes('/segments/')) return json({ found: true, job_id: 'history-batch', candidate_index: pathname.endsWith('history_01.mp4') ? 0 : 1, candidate_count: 2, note: '历史自定义时长', duration: 6.5, ratio: '9:16', resolution: '480p', generate_audio: false, exact_duration: true, seed: 100, actual_duration: 6.5, width: 480, height: 854, has_audio: false })
  if (pathname.endsWith('/compose')) { compositions.push(request.postDataJSON()); return json({ prompt: request.postDataJSON().video_prompt || 'mock prompt', warnings: ['模拟编排提醒：请确认动作描述完整'], video_backend: 'comfyui', video_workflow: cfg.video_workflow, video_sources: (request.postDataJSON().video_sources || []).map(source => ({ ...source, expected_sha256: 'a'.repeat(64), start: 1, end: 4 })) }) }
  if (pathname.endsWith('/segment/video')) {
    assert.equal([...jobs.values()].filter(j => j.status === 'running').length, 0, 'only one video may be submitted at a time')
    const jobId = `job${submissions.length + 1}`
    submissions.push(request.postDataJSON())
    const data = request.postDataJSON(), total = data.candidate_count || 1
    const candidates = Array.from({ length: total }, (_, index) => ({ index, seed: (data.seed ?? 12) + index, file: total === 1 ? `${jobId}.mp4` : `${jobId}_${index + 1}.mp4` }))
    jobs.set(jobId, { job_id: jobId, status: 'running', failed: failNext, failIndex: failCandidateIndex, hold: heldJob, total, candidates }); failNext = false; failCandidateIndex = null
    return json({ job_id: jobId, total, candidates })
  }
  if (pathname.startsWith('/api/segment-jobs/')) {
    const job = jobs.get(pathname.split('/').at(-1))
    if (!job.hold) job.status = job.failed ? 'failed' : 'succeeded'
    const results = job.candidates.map(c => ({ ...c, status: job.hold ? 'running' : job.failed || c.index === job.failIndex ? 'failed' : 'succeeded', error: job.failed || c.index === job.failIndex ? '模拟任务失败' : '', video_url: !job.hold && !job.failed && c.index !== job.failIndex ? `/files/${taskId}/segments/${c.file}` : '' }))
    return json({ ...job, results, done: job.hold ? 0 : job.total, error: job.failed ? '模拟任务失败' : job.failIndex != null ? '1 个候选失败，已保留成功结果' : '', video_url: results.find(r => r.status === 'succeeded')?.video_url || '' })
  }
  if (pathname.endsWith('/canvas-export') && method === 'POST') { exportRequest = request.postDataJSON(); return json({ job_id: 'abcdef123456' }) }
  if (pathname.includes('/canvas-export/')) return json({ status: 'succeeded', done: exportRequest.files.length, total: exportRequest.files.length, url: `/files/${taskId}/export/final.mp4` })
  if (pathname.endsWith('/materials/upload')) {
    project.assets.push({ kind: 'image', name: '上传参考图', images: ['upload.webp'] })
    return json({ kind: 'image', index: project.assets.length - 1, name: '上传参考图', entry: project.assets.at(-1) })
  }
  unexpected.push(`${method} ${pathname}`)
  return route.fulfill({ status: 404, contentType: 'application/json', body: JSON.stringify({ detail: 'Mock route missing' }) })
})

async function assertNoOverflow() {
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
}
async function waitSaved() { await page.waitForFunction(() => document.querySelector('.save-state')?.textContent.includes('已保存')) }
async function selectCreation(index) {
  if (await page.locator('.sequence-toggle').getAttribute('aria-expanded') === 'false') await page.locator('.sequence-toggle').click()
  await page.locator('.sequence-shot').nth(index).click()
}
async function emptyCanvasPoint() {
  return page.locator('.flow-board').evaluate(board => {
    const rect = board.getBoundingClientRect()
    for (let y = rect.top + 75; y < rect.bottom - 70; y += 35) {
      for (let x = rect.left + 100; x < rect.right - 70; x += 35) {
        if (document.elementFromPoint(x, y) === board) return { x, y }
      }
    }
    throw new Error('No empty canvas point found')
  })
}
async function assertComposerAligned() {
  await page.waitForFunction(() => {
    const card = document.querySelector('.flow-node.shot.selected')?.getBoundingClientRect()
    const editor = document.querySelector('.video-composer')?.getBoundingClientRect()
    return card && editor && Math.abs(card.x + card.width / 2 - editor.x - editor.width / 2) < 2 && Math.abs(editor.y - card.bottom - 14) < 2
  })
}
async function openCanvas() { await page.goto(`${url}/?browser-test=canvas#project=${taskId}&view=storyboard`); await page.locator('.flow-node').first().waitFor() }
fs.mkdirSync('docs/_shots', { recursive: true })
try {
  await page.goto(url)
  await page.getByRole('heading', { name: '你的下一部作品，从这里开始。' }).waitFor()
  await assertNoOverflow()
  await page.waitForTimeout(450)
  await page.screenshot({ path: 'docs/images/home.png' })
  await page.locator('.template-card').first().click()
  await page.locator('.story-sequence').waitFor()
  assert.equal(await page.locator('.flow-node.shot').count(), 3, 'home template creates one editable card per video')
  assert.equal(await page.locator('.flow-node.video').count(), 0)
  await page.getByRole('textbox', { name: '视频画面描述' }).waitFor()
  assert.equal(submissions.length, 0)
  await waitSaved()
  await page.goto(`${url}/?browser-test=home`)
  await page.getByRole('heading', { name: '你的下一部作品，从这里开始。' }).waitFor()

  graph = emptyWorkflow()
  const scene = makeNode('material', 80, 120, { title: '山海晨光', materialKind: 'scene', materialName: '山海晨光', materialFile: 'morning.webp' })
  graph.nodes.push(scene, makeNode('material', 80, 440, { title: '未寄出的信', materialKind: 'prop', materialName: '未寄出的信', materialFile: 'letter.webp' }))
  const shots = appendStoryboard(graph, ['晨光穿过山间薄雾，远景建立环境，镜头缓慢推进。', '主角走进山海之间，停下脚步，望向远处。', '主角展开手中的信，静态特写，留下一个温柔的悬念。'], { duration: 5, sources: [scene.id] })
  shots.forEach((shot, index) => {
    shot.x = 430 + index * 365; shot.y = 120; shot.data.manual = true
    // Simulate a saved project from before the redesign.
    const video = makeNode('video', shot.x, 440, { title: '旧视频输出', status: 'empty' })
    graph.nodes.push(video); graph.edges.push({ source: shot.id, target: video.id, id: `legacy-${index}` })
  })
  graph.viewport = { x: -20, y: -20, zoom: .68 }
  await openCanvas()
  await waitSaved()
  assert.equal(await page.locator('.flow-node.video').count(), 0, 'legacy output cards merge on load')
  assert.equal(await page.locator('.flow-node.shot').count(), 3)
  assert.equal(await page.locator('.flow-inspector').count(), 0)
  await page.getByRole('button', { name: '显示全部节点', exact: true }).click()
  await waitSaved()
  await page.screenshot({ path: 'docs/images/storyboard-gallery.png' })
  await selectCreation(0)
  await assertComposerAligned()
  const beforePan = await page.locator('.video-composer').boundingBox()
  const panPoint = await emptyCanvasPoint()
  await page.mouse.move(panPoint.x, panPoint.y)
  await page.mouse.down({ button: 'middle' })
  await page.mouse.move(panPoint.x - 40, panPoint.y + 25, { steps: 5 })
  await page.mouse.up({ button: 'middle' })
  await assertComposerAligned()
  const afterPan = await page.locator('.video-composer').boundingBox()
  assert.ok(Math.abs(afterPan.x - beforePan.x + 40) < 2 && Math.abs(afterPan.y - beforePan.y - 25) < 2, 'editor follows canvas pan instead of remaining at the screen bottom')
  const header = await page.locator('.flow-node.shot.selected .node-header').boundingBox()
  await page.mouse.move(header.x + 70, header.y + header.height / 2)
  await page.mouse.down()
  await page.mouse.move(header.x + 95, header.y + header.height / 2 - 20, { steps: 5 })
  await page.mouse.up()
  await assertComposerAligned()
  const afterDrag = await page.locator('.video-composer').boundingBox()
  assert.ok(Math.abs(afterDrag.x - afterPan.x - 25) < 2 && Math.abs(afterDrag.y - afterPan.y + 20) < 2, 'editor follows the selected card when it is dragged')
  const preview = await page.locator('.flow-node.shot.selected .node-preview').boundingBox()
  await waitSaved()
  const dragViewport = structuredClone(graph.viewport)
  await page.mouse.move(preview.x + preview.width / 2, preview.y + preview.height / 2)
  await page.mouse.down()
  await page.mouse.move(preview.x + preview.width / 2 + 35, preview.y + preview.height / 2 + 20, { steps: 5 })
  await page.mouse.up()
  await assertComposerAligned()
  const afterPreviewDrag = await page.locator('.video-composer').boundingBox()
  assert.ok(Math.abs(afterPreviewDrag.x - afterDrag.x - 35) < 2 && Math.abs(afterPreviewDrag.y - afterDrag.y - 20) < 2, 'the whole empty preview drags its card and editor')
  await waitSaved()
  assert.deepEqual(graph.viewport, dragViewport, 'dragging a node preview does not pan the canvas')
  await page.getByRole('button', { name: '放大画布', exact: true }).click()
  await assertComposerAligned()
  const afterZoom = await page.locator('.video-composer').boundingBox()
  assert.ok(Math.abs(afterZoom.width - beforePan.width) < 2, 'zooming keeps the editor text at a readable size')
  await selectCreation(1)
  await assertComposerAligned()
  await selectCreation(0)
  await assertComposerAligned()
  await page.screenshot({ path: 'docs/_shots/video-composer-anchored.png' })
  await page.getByRole('button', { name: '运镜', exact: true }).click()
  await page.getByRole('button', { name: '缓慢推进', exact: true }).click()
  assert.ok(await page.getByRole('textbox', { name: '视频画面描述' }).textContent())
  await waitSaved()
  await page.getByRole('button', { name: '关闭视频输入框' }).click()
  await page.getByRole('button', { name: '批量生成', exact: true }).click()
  await page.getByRole('dialog').waitFor()
  assert.equal(await page.locator('.review-list article:not(.blocked)').count(), 3)
  await page.screenshot({ path: 'docs/_shots/generation-review.png' })
  await page.getByRole('button', { name: '开始生成 3 镜', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.node-state i.succeeded').length === 3)
  assert.equal(submissions.length, 3)
  assert.ok(submissions.every(s => s.frames.length === 1 && s.duration === 5 && s.expected_workflow === 'i2v'))
  await page.getByRole('button', { name: '导出视频', exact: true }).click()
  await page.getByRole('button', { name: /^合成成片/ }).click()
  await page.getByRole('button', { name: '导出 3 镜成片', exact: true }).click()
  await page.getByRole('link', { name: '下载成片', exact: true }).waitFor()
  assert.deepEqual(exportRequest.files, ['job1.mp4', 'job2.mp4', 'job3.mp4'])

  await selectCreation(0)
  failNext = true
  await assertComposerAligned(); await waitSaved()
  const playablePreview = page.locator('.flow-node.shot.selected .node-preview')
  const playableBefore = await playablePreview.boundingBox()
  await page.mouse.move(playableBefore.x + playableBefore.width / 3, playableBefore.y + playableBefore.height / 3)
  await page.mouse.down()
  await page.mouse.move(playableBefore.x + playableBefore.width / 3 + 20, playableBefore.y + playableBefore.height / 3 + 15, { steps: 5 })
  await page.mouse.up()
  const playableAfter = await playablePreview.boundingBox()
  assert.ok(Math.abs(playableAfter.x - playableBefore.x - 20) < 2 && Math.abs(playableAfter.y - playableBefore.y - 15) < 2, `completed videos drag from the picture area: ${JSON.stringify({ playableBefore, playableAfter })}`)
  await assertComposerAligned()
  await page.mouse.move(playableAfter.x + playableAfter.width / 2, playableAfter.y + playableAfter.height - 10)
  await page.mouse.down()
  await page.mouse.move(playableAfter.x + playableAfter.width / 2 + 15, playableAfter.y + playableAfter.height - 10, { steps: 5 })
  await page.mouse.up()
  assert.deepEqual(await playablePreview.boundingBox(), playableAfter, 'native video controls do not drag the node')
  await page.locator('.video-composer').getByRole('button', { name: '生成视频', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.composer-message')?.textContent.includes('模拟任务失败'))
  await page.locator('.composer-warnings summary').click()
  assert.ok(await page.getByText('模拟编排提醒：请确认动作描述完整', { exact: true }).isVisible())
  assert.equal(submissions.length, 4)
  await waitSaved()
  assert.equal(graph.nodes.flatMap(n => n.data.versions || []).filter(v => v.status === 'succeeded').length, 3, 'previous successful versions remain inside their creation cards')
  assert.equal(await page.locator('.flow-node.video').count(), 0)
  assert.equal(await page.locator('.flow-node.shot').count(), 3)
  assert.ok(await page.locator('.video-composer').getByRole('button', { name: '1 个版本' }).isVisible())

  // Pause leaves the submitted job running, and refresh never silently resumes paid queued work.
  heldJob = true
  await selectCreation(1)
  await page.locator('.video-composer').getByRole('button', { name: '生成视频', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.node-state i.running').length === 1)
  await selectCreation(2)
  await page.locator('.video-composer').getByRole('button', { name: '生成视频', exact: true }).click()
  await page.getByRole('button', { name: '打开生成队列' }).click()
  await page.getByRole('button', { name: '暂停队列', exact: true }).click()
  jobs.get('job5').hold = false; heldJob = false
  await page.waitForFunction(() => document.querySelectorAll('.node-state i.running').length === 0)
  await waitSaved()
  assert.equal(submissions.length, 5)
  await page.reload()
  await page.getByRole('button', { name: '继续队列', exact: true }).waitFor()
  assert.equal(submissions.length, 5)
  await page.getByRole('button', { name: '继续队列', exact: true }).click()
  await page.waitForFunction(() => !document.querySelector('.node-state i:is(.queued, .running, .composing)'))
  assert.equal(submissions.length, 6)
  await waitSaved()

  // The same card can play an older version, and export starts with the chosen version.
  await selectCreation(1)
  await page.locator('.video-composer').getByRole('button', { name: '2 个版本' }).click()
  assert.ok(await page.locator('.composer-warnings summary').isVisible(), 'prompt reminders survive reload')
  await page.getByRole('button', { name: /^版本 1/ }).click()
  const secondCard = page.locator(`[data-node-id="${shots[1].id}"]`)
  assert.ok((await secondCard.locator('video').getAttribute('src')).endsWith('/job2.mp4'))
  await waitSaved()
  await page.getByRole('button', { name: '导出视频', exact: true }).click()
  assert.equal(await page.getByRole('combobox', { name: '视频 02导出版本' }).inputValue(), 'job2.mp4')
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()

  // A failed save must never submit a paid generation, even if the user tries to resume.
  await selectCreation(0)
  saveFailure = true
  await page.locator('.video-composer').getByRole('button', { name: '生成视频', exact: true }).click()
  await page.getByText('模拟保存失败', { exact: true }).first().waitFor()
  assert.equal(submissions.length, 6)
  saveFailure = false
  await page.getByRole('button', { name: '重试保存', exact: true }).click()
  await waitSaved()
  await page.getByRole('button', { name: '移除等待中的 1 镜', exact: true }).click()

  await waitSaved()
  await page.reload()
  await page.locator('.flow-node').first().waitFor()
  await page.getByRole('button', { name: '更多画布操作', exact: true }).click()
  await page.getByRole('button', { name: '剧本建镜', exact: true }).click()
  await page.getByRole('textbox', { name: '分段镜头描述' }).fill('新镜头一\n\n新镜头二')
  await page.getByRole('button', { name: '创建 2 个分镜', exact: true }).click()
  assert.equal(await page.locator('.flow-node.shot').count(), 5)
  await page.locator('input[type=file][accept="image/png,image/jpeg,image/webp"]').setInputFiles({ name: 'reference.webp', mimeType: 'image/webp', buffer: fs.readFileSync('web/public/images/inspiration-mountain.webp') })
  await page.waitForFunction(() => [...document.querySelectorAll('.flow-node.material strong')].some(n => n.textContent === '上传参考图'))
  await page.locator('.composer-references').getByRole('img', { name: '上传参考图', exact: true }).waitFor()
  const backup = emptyWorkflow(); backup.nodes.push(makeShot(0, 0))
  await page.getByRole('button', { name: '更多画布操作', exact: true }).click()
  await page.getByRole('button', { name: '导入画布备份', exact: true }).click({ noWaitAfter: true })
  await page.locator('input[type=file][accept=".json,application/json"]').setInputFiles({ name: 'story.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(backup)) })
  await page.waitForFunction(() => document.querySelectorAll('.flow-node.shot').length === 6)
  await selectCreation(0)
  await page.getByRole('button', { name: '复制创作', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.flow-node.shot').length === 7)
  await waitSaved()
  assert.deepEqual(graph.nodes.find(n => n.data.title.endsWith(' · 副本')).data.versions, [], 'copying a creation never duplicates a job or its output')

  // Parameters in the LibTV-style panel really reach the backend, and partial success remains usable.
  await selectCreation(0)
  await page.getByRole('button', { name: '视频生成设置', exact: true }).click()
  await page.getByRole('button', { name: '9:16', exact: true }).click()
  await page.getByRole('button', { name: '480P', exact: true }).click()
  const durationInput = page.getByRole('spinbutton', { name: '视频时长', exact: true })
  assert.equal(await durationInput.getAttribute('min'), '1')
  assert.equal(await durationInput.getAttribute('max'), '15')
  assert.equal(await page.getByRole('slider', { name: '视频时长滑块' }).getAttribute('min'), '1')
  await durationInput.fill('1')
  await durationInput.press('Tab')
  await waitSaved()
  assert.equal(graph.nodes.find(n => n.id === shots[0].id).data.duration, 1)
  await page.getByRole('spinbutton', { name: '视频时长', exact: true }).fill('6.5')
  await page.getByRole('spinbutton', { name: '视频时长', exact: true }).press('Tab')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '2个', exact: true }).click()
  await page.getByText('高级设置', { exact: true }).click()
  await page.getByRole('spinbutton', { name: '视频随机种子' }).fill('100')
  await page.getByRole('spinbutton', { name: '视频随机种子' }).press('Tab')
  await page.locator('.toast .x').evaluateAll(buttons => buttons.forEach(b => b.click()))
  await page.locator('.generation-settings').evaluate(el => { el.scrollTop = 0 })
  await page.screenshot({ path: 'docs/_shots/video-generation-settings.png' })
  assert.ok(await page.locator('.generation-settings').isVisible(), 'editing settings inside the popup leaves it open')
  const descriptionBeforeDismiss = await page.getByRole('textbox', { name: '视频画面描述' }).textContent()
  await page.locator('.composer-heading input').click()
  assert.equal(await page.locator('.generation-settings').count(), 0, 'clicking elsewhere in the editor dismisses only its settings')
  assert.equal(await page.locator('.video-composer').count(), 1)
  await page.getByRole('button', { name: '视频生成设置', exact: true }).click()
  const dismissPoint = await emptyCanvasPoint()
  await page.mouse.move(dismissPoint.x, dismissPoint.y)
  await page.mouse.down({ button: 'middle' })
  await page.mouse.move(dismissPoint.x + 25, dismissPoint.y - 15, { steps: 5 })
  await page.mouse.up({ button: 'middle' })
  assert.equal(await page.locator('.video-composer').count(), 1, 'dragging the canvas does not dismiss the editor')
  assert.ok(await page.locator('.generation-settings').isVisible(), 'dragging the canvas does not dismiss settings')
  const blankPoint = await emptyCanvasPoint()
  await page.mouse.click(blankPoint.x, blankPoint.y)
  assert.equal(await page.locator('.video-composer').count(), 0, 'clicking empty canvas dismisses both editor and settings')
  assert.equal(await page.locator('.generation-settings').count(), 0)
  await selectCreation(0)
  assert.equal(await page.getByRole('textbox', { name: '视频画面描述' }).textContent(), descriptionBeforeDismiss)
  await page.getByRole('button', { name: '视频生成设置', exact: true }).click()
  assert.equal(await page.getByRole('spinbutton', { name: '视频时长', exact: true }).inputValue(), '6.5')
  assert.equal(await page.getByRole('button', { name: '9:16', exact: true }).getAttribute('aria-pressed'), 'true')
  await page.getByRole('button', { name: '关闭视频生成设置' }).click()
  failCandidateIndex = 1
  await page.locator('.video-composer').getByRole('button', { name: '生成视频', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.composer-message')?.textContent.includes('1 个候选失败'))
  await waitSaved()
  assert.equal(submissions.length, 7)
  assert.deepEqual({ ratio: submissions.at(-1).ratio, resolution: submissions.at(-1).resolution, duration: submissions.at(-1).duration, count: submissions.at(-1).candidate_count, audio: submissions.at(-1).generate_audio, seed: submissions.at(-1).seed }, { ratio: '9:16', resolution: '480p', duration: 6.5, count: 2, audio: false, seed: 100 })
  const recent = graph.nodes.find(n => n.id === shots[0].id).data.versions.filter(v => v.jobId === 'job7')
  assert.deepEqual(recent.map(v => v.status), ['succeeded', 'failed'])
  await page.getByRole('button', { name: '对比候选', exact: true }).click()
  await page.getByRole('dialog', { name: '对比视频候选' }).waitFor()
  assert.equal(await page.getByRole('dialog').locator('video').count(), 2)
  await page.waitForFunction(() => [...document.querySelectorAll('.compare-dialog video')].every(v => v.readyState >= 2))
  await page.screenshot({ path: 'docs/_shots/video-candidate-compare.png' })
  await page.getByRole('dialog').getByRole('button', { name: '使用这个版本', exact: true }).first().click()
  await page.getByRole('button', { name: '关闭候选对比' }).click()
  await waitSaved()
  await page.reload()
  await page.locator('.flow-node').first().waitFor()
  assert.equal(graph.nodes.find(n => n.id === shots[0].id).data.duration, 6.5)

  // Empty-space gestures cannot create cards; the explicit plus creates one linked next shot.
  await selectCreation(0)
  const cardCount = await page.locator('.flow-node.shot').count()
  const emptyPoint = await emptyCanvasPoint()
  await page.mouse.dblclick(emptyPoint.x, emptyPoint.y)
  await page.keyboard.press('n')
  assert.equal(await page.locator('.flow-node.shot').count(), cardCount)
  await selectCreation(0)
  await page.getByRole('button', { name: '添加视频', exact: true }).click()
  await page.getByRole('button', { name: '空白视频', exact: true }).click()
  assert.equal(await page.locator('.flow-node.shot').count(), cardCount + 1)
  await waitSaved()
  const newShot = graph.nodes.filter(n => n.type === 'shot').at(-1)
  assert.ok(graph.edges.some(e => e.source === shots[0].id && e.target === newShot.id))
  assert.equal(await page.locator('.video-source select').first().inputValue(), 'text')
  assert.equal(submissions.length, 7, 'adding a video never submits generation')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await waitSaved()
  assert.equal(await page.locator('.flow-node.shot').count(), cardCount)

  // Plus continuation pins the selected success and keeps inherited material links.
  cfg.video_workflow = 'ref2va'
  await page.reload()
  await page.locator('.flow-node').first().waitFor()
  await selectCreation(0)
  await page.getByRole('button', { name: '添加视频', exact: true }).click()
  await page.getByRole('button', { name: '续拍当前视频', exact: true }).click()
  await waitSaved()
  const continuation = graph.nodes.filter(n => n.type === 'shot').at(-1)
  const sourceEdge = graph.edges.find(e => e.target === continuation.id && e.source === shots[0].id)
  assert.equal(sourceEdge.usage, 'continue')
  assert.ok(sourceEdge.sourceVersionId)
  assert.ok(graph.edges.some(e => e.target === continuation.id && graph.nodes.find(n => n.id === e.source)?.type === 'material'))
  assert.equal(await page.locator('.video-source select').first().inputValue(), 'continue')
  assert.equal(submissions.length, 7)
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await waitSaved()

  // Lost canvas records can be rebuilt as one creation with all candidates and exact settings.
  historicalRecords = [1, 2].map(i => ({ name: `history_0${i}.mp4`, url: `/files/${taskId}/segments/history_0${i}.mp4` }))
  await page.getByRole('button', { name: '更多画布操作', exact: true }).click()
  await page.getByRole('button', { name: '导入生成记录', exact: true }).click()
  await page.waitForFunction(() => document.querySelectorAll('.flow-node.shot').length === 8)
  await waitSaved()
  const restored = graph.nodes.find(n => n.data.versions?.some(v => v.jobId === 'history-batch'))
  assert.equal(restored.data.versions.length, 2)
  assert.equal(restored.data.duration, 6.5)
  assert.equal(restored.data.generateAudio, false)
  assert.equal(restored.data.versions[0].actual_duration, 6.5)
  assert.equal(submissions.length, 7, 'importing historical candidates never submits another generation')

  await page.setViewportSize({ width: 390, height: 844 })
  await selectCreation(0)
  await page.locator('.sequence-toggle').click()
  await assertComposerAligned()
  const mobileEditor = await page.locator('.video-composer').boundingBox()
  const mobileBoard = await page.locator('.flow-board').boundingBox()
  assert.ok(mobileEditor.x >= 0 && mobileEditor.x + mobileEditor.width <= 390 && mobileEditor.y + mobileEditor.height <= mobileBoard.y + mobileBoard.height, 'the card and anchored editor fit together on mobile')
  await assertNoOverflow()
  await page.locator('.toast .x').evaluateAll(buttons => buttons.forEach(b => b.click()))
  await page.waitForTimeout(350)
  await page.screenshot({ path: 'docs/_shots/canvas-mobile.png' })
  await page.getByRole('button', { name: '视频生成设置', exact: true }).click()
  await page.locator('.generation-settings').evaluate(el => { el.scrollTop = 0 })
  const mobilePanel = await page.locator('.generation-settings').boundingBox()
  assert.ok(mobilePanel.x >= 0 && mobilePanel.x + mobilePanel.width <= 390 && mobilePanel.y >= 0, 'mobile settings stay inside the viewport')
  await assertNoOverflow()
  await page.screenshot({ path: 'docs/_shots/video-settings-mobile.png' })
  await page.getByRole('button', { name: '关闭视频生成设置' }).click()
  await page.goto(`${url}/?browser-test=mobile-home`)
  await page.getByRole('heading', { name: '你的下一部作品，从这里开始。' }).waitFor()
  await assertNoOverflow()
  await page.waitForTimeout(450)
  await page.screenshot({ path: 'docs/_shots/home-mobile.png' })

  // Cleaning the obsolete video form must preserve every material-editing entry point.
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto(`${url}/?browser-test=materials#project=${taskId}&view=studio`)
  const sceneCard = page.locator('.mcard').filter({ has: page.getByText('山海晨光', { exact: true }) })
  await sceneCard.waitFor()
  assert.equal(await page.locator('.workbench .compose').count(), 0)
  await sceneCard.getByRole('button', { name: '编辑', exact: true }).click()
  assert.equal(await page.getByRole('textbox', { name: '素材名字' }).inputValue(), '山海晨光')
  await page.locator('.edit-form').getByRole('button', { name: '取消', exact: true }).click()
  await sceneCard.getByRole('button', { name: '提示词', exact: true }).click()
  await page.getByRole('dialog', { name: '提示词', exact: true }).waitFor()
  assert.equal(await page.getByRole('textbox', { name: '山海晨光 的提示词' }).inputValue(), project.assets[0].anchor)
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await sceneCard.getByRole('button', { name: 'AI 生成', exact: true }).click()
  await page.getByRole('dialog', { name: 'AI 生成素材图' }).waitFor()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await sceneCard.getByRole('button', { name: '生成历史', exact: true }).click()
  await page.getByRole('dialog', { name: '山海晨光 生成历史' }).getByText('正在使用', { exact: true }).waitFor()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await sceneCard.locator('.mthumb img').click()
  await page.getByRole('dialog', { name: '山海晨光 素材图预览' }).waitFor()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: 'AI 助手', exact: true }).click()
  await page.getByRole('dialog', { name: '素材规划助手' }).waitFor()
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: /^生成记录/ }).click()
  await page.getByRole('button', { name: '用了什么', exact: true }).first().click()
  await page.getByText('480 × 854', { exact: true }).waitFor()
  assert.ok(await page.getByText('成片无音轨', { exact: true }).isVisible())
  assert.equal(submissions.length, 7)
  // Exercise the full visual-source payload and persistence through the real Vue UI.
  await page.goto(`${url}/?browser-test=continuation#project=${taskId}&view=storyboard`)
  await page.locator('.flow-node').first().waitFor()
  await selectCreation(0)
  await page.getByRole('button', { name: '添加视频', exact: true }).click()
  await page.getByRole('button', { name: '续拍当前视频', exact: true }).click()
  await page.getByRole('textbox', { name: '视频画面描述' }).fill('从当前结束状态继续，主角抬头看向远处。')
  await waitSaved()
  const continuationId = graph.nodes.filter(n => n.type === 'shot').at(-1).id
  const sourceChoice = structuredClone(graph.edges.find(e => e.target === continuationId && e.usage === 'continue'))
  const versionsBefore = graph.nodes.find(n => n.id === sourceChoice.source).data.versions
  const sourceFile = versionsBefore.find(v => v.id === sourceChoice.sourceVersionId).file
  await page.locator('.video-composer').getByRole('button', { name: '生成视频', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.composer-message')?.textContent.includes('重新生成会保留已有版本'))
  await waitSaved()
  assert.equal(submissions.length, 8)
  assert.equal(submissions.at(-1).video_sources[0].file, sourceFile)
  assert.equal(submissions.at(-1).video_sources[0].usage, 'continue')
  assert.equal(submissions.at(-1).video_sources[0].expected_sha256, 'a'.repeat(64))
  assert.equal(graph.nodes.find(n => n.id === continuationId).data.versions[0].videoSources[0].file, sourceFile)
  await page.screenshot({ path: 'docs/_shots/video-continuation.png' })
  await page.reload()
  await page.locator('.flow-node').first().waitFor()
  await selectCreation(graph.nodes.filter(n => n.type === 'shot').findIndex(n => n.id === continuationId))
  assert.equal(await page.locator('.video-source select').first().inputValue(), 'continue')
  assert.equal(await page.locator('.video-source select').nth(1).inputValue(), sourceChoice.sourceVersionId)
  await page.setViewportSize({ width: 390, height: 844 })
  if (await page.locator('.sequence-toggle').getAttribute('aria-expanded') === 'true') await page.locator('.sequence-toggle').click()
  await assertComposerAligned()
  await assertNoOverflow()
  // Mention editing is exercised against the real Vue UI; all requests remain mocked.
  await page.setViewportSize({ width: 1440, height: 1000 })
  cfg.video_workflow = 'ref2va'
  graph = emptyWorkflow()
  const mentionShot = makeShot(440, 100, 1)
  const mentionScene = makeNode('material', 70, 100, { title: '山海晨光', materialKind: 'scene', materialName: '山海晨光' })
  graph.nodes.push(mentionScene, mentionShot)
  graph.edges.push({ id: 'mention-scene', source: mentionScene.id, target: mentionShot.id })
  await openCanvas(); await selectCreation(0)
  assert.equal(await page.locator('.flow-node.shot .node-preview img').count(), 0, 'reference material never masquerades as a generated video')
  assert.equal(await page.locator('.composer-references img').count(), 1)
  const promptBox = page.getByRole('textbox', { name: '视频画面描述' })
  await promptBox.fill('@')
  await page.getByRole('option', { name: /山海晨光/ }).waitFor()
  assert.equal(await page.getByRole('option', { name: /未寄出的信/ }).count(), 0, '@ only lists this creation’s connected materials')
  await promptBox.pressSequentially('未寄')
  assert.equal(await page.locator('.mention-menu').getByRole('option').count(), 0)
  assert.equal(graph.nodes.length, 2, '@ never creates an unrelated reference node')
  await promptBox.press('Escape')
  await page.locator('.video-composer').getByRole('button', { name: /参考素材/ }).click()
  await page.locator('.drawer-material').filter({ hasText: '未寄出的信' }).click()
  await page.locator('.composer-references img').nth(1).waitFor()
  assert.deepEqual(await page.locator('.reference-number').allTextContents(), ['1', '2'])
  assert.deepEqual(await page.locator('.reference-chip').evaluateAll(elements => elements.map(el => el.getAttribute('aria-label'))), ['素材 1：未寄出的信', '素材 2：山海晨光'])
  await page.locator('.reference-chip').first().hover()
  await page.getByRole('tooltip', { name: '未寄出的信 放大预览' }).waitFor()
  assert.ok((await page.locator('.reference-hover-preview img').boundingBox()).width > 150)
  await page.screenshot({ path: 'docs/_shots/reference-hover.png' })
  await promptBox.hover()
  assert.equal(await page.locator('.reference-hover-preview').count(), 0, 'moving off the thumbnail closes the enlarged preview')
  await promptBox.fill('人物拿着 ')
  await promptBox.press('End'); await promptBox.pressSequentially('@未寄')
  await page.getByRole('option', { name: /未寄出的信/ }).click()
  await promptBox.pressSequentially('走进 ')
  await promptBox.pressSequentially('@山海')
  await promptBox.press('Enter')
  await promptBox.pressSequentially('，镜头缓慢跟拍。')
  assert.equal(await page.locator('.prompt-mention').count(), 2)
  assert.equal(await page.locator('.composer-references img').count(), 2, 'mention selection leaves the chosen references unchanged')
  await waitSaved()
  const savedPrompt = graph.nodes.find(n => n.id === mentionShot.id).data.description
  assert.ok(savedPrompt.includes(mentionToken({ kind: 'prop', name: '未寄出的信' })))
  assert.ok(savedPrompt.includes(mentionToken({ kind: 'scene', name: '山海晨光' })))
  await page.screenshot({ path: 'docs/_shots/prompt-mentions.png' })
  await page.reload(); await page.locator('.flow-node').first().waitFor(); await selectCreation(0)
  assert.equal(await page.locator('.prompt-mention').count(), 2, 'saved references restore as inline chips')
  await page.getByRole('button', { name: '断开 未寄出的信', exact: true }).click()
  assert.equal(await page.locator('.prompt-mention.missing').count(), 1)
  const beforeMissing = submissions.length
  await page.locator('.video-composer').getByRole('button', { name: '生成视频', exact: true }).click()
  assert.equal(submissions.length, beforeMissing, 'unconnected mentions stop generation')
  await promptBox.press('Control+End'); await promptBox.pressSequentially(' @未寄')
  assert.equal(await page.getByRole('option', { name: /未寄出的信/ }).count(), 0, 'disconnecting immediately removes the material from @ choices')
  await promptBox.press('Escape')
  await page.locator('.video-composer').getByRole('button', { name: /参考素材/ }).click()
  await page.locator('.drawer-material').filter({ hasText: '未寄出的信' }).click()
  await promptBox.press('Control+End')
  await page.getByRole('option', { name: /未寄出的信/ }).click()
  assert.equal(await page.locator('.prompt-mention.missing').count(), 0)
  // Chinese composition must not accidentally select a material or submit a clip.
  await promptBox.dispatchEvent('compositionstart')
  await promptBox.press('Enter')
  assert.equal(submissions.length, beforeMissing)
  await promptBox.dispatchEvent('compositionend')
  await waitSaved()
  await promptBox.press('Control+Enter')
  await page.waitForFunction(() => document.querySelector('.composer-message')?.textContent.includes('重新生成会保留已有版本'))
  assert.ok(compositions.at(-1).description.includes('@{prop:'))
  assert.deepEqual(compositions.at(-1).props, ['未寄出的信'])
  assert.equal(compositions.at(-1).scene, '山海晨光')
  await promptBox.fill('第一行')
  await promptBox.press('End'); await promptBox.press('Enter')
  await promptBox.pressSequentially('@未寄')
  await promptBox.press('Enter')
  assert.equal(await page.locator('.prompt-mention').count(), 1, 'mentions work after a line break')
  await promptBox.press('Control+z')
  assert.equal(await page.locator('.prompt-mention').count(), 0, 'mention insertion supports native undo')
  await promptBox.press('Control+Shift+z')
  assert.equal(await page.locator('.prompt-mention').count(), 1, 'mention insertion supports native redo')
  await promptBox.press('Control+End'); await promptBox.press('Backspace'); await promptBox.press('Backspace')
  assert.equal(await page.locator('.prompt-mention').count(), 0, 'a mention deletes as a single item')
  await promptBox.fill('前文 后文')
  await promptBox.press('Home'); await promptBox.press('ArrowRight'); await promptBox.press('ArrowRight'); await promptBox.press('ArrowRight')
  await promptBox.pressSequentially('@山海'); await promptBox.press('Enter')
  assert.ok((await promptBox.textContent()).includes('前文 @山海晨光 后文'), 'choosing a mention preserves text after the caret')
  await promptBox.press('Control+a')
  const clipboard = await promptBox.evaluate(element => {
    const data = new DataTransfer()
    element.dispatchEvent(new ClipboardEvent('copy', { clipboardData: data, bubbles: true, cancelable: true }))
    return { text: data.getData('text/plain'), tokens: data.getData('application/x-frameflow-prompt') }
  })
  assert.ok(clipboard.text.includes('@山海晨光') && !clipboard.text.includes('@{'))
  await promptBox.fill('')
  await promptBox.evaluate((element, clipboard) => {
    const data = new DataTransfer()
    data.setData('text/plain', clipboard.text); data.setData('application/x-frameflow-prompt', clipboard.tokens)
    element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }))
  }, clipboard)
  assert.equal(await page.locator('.prompt-mention').count(), 1, 'internal copy/paste retains reference identity')
  await promptBox.press('Control+End')
  await promptBox.evaluate(element => {
    const data = new DataTransfer()
    data.setData('text/plain', '<img src=x onerror=alert(1)>'); data.setData('text/html', '<script>throw new Error("unsafe")</script>')
    element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }))
  })
  assert.equal(await promptBox.locator('script, img:not(.prompt-mention img)').count(), 0, 'pasted HTML cannot create elements')
  await page.setViewportSize({ width: 390, height: 844 })
  if (await page.locator('.sequence-toggle').getAttribute('aria-expanded') === 'true') await page.locator('.sequence-toggle').click()
  await promptBox.press('Control+End'); await promptBox.pressSequentially(' @')
  const mentionMenu = await page.locator('.mention-menu').boundingBox()
  assert.ok(mentionMenu.x >= 0 && mentionMenu.x + mentionMenu.width <= 390 && mentionMenu.y >= 0 && mentionMenu.y + mentionMenu.height <= 844)
  await promptBox.press('Escape')
  await assertNoOverflow()
  // Theme switches apply to the entire app, including previews teleported to body.
  await page.setViewportSize({ width: 1440, height: 1000 })
  const css = async (selector, property) => page.locator(selector).first().evaluate((el, property) => getComputedStyle(el)[property], property)
  assert.equal(await css('.flow-board', 'backgroundColor'), 'rgb(17, 18, 22)')
  await page.getByRole('button', { name: '切换白天模式', exact: true }).click()
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light')
  assert.equal(await page.evaluate(() => localStorage.getItem('frameflow.theme')), 'light')
  assert.equal(await css('.flow-board', 'backgroundColor'), 'rgb(245, 245, 245)')
  // Opening a selected card after the outside-click theme switch preserves its prompt.
  await selectCreation(0)
  assert.equal(await css('.flow-node.shot', 'backgroundColor'), 'rgba(0, 0, 0, 0)')
  assert.equal(await css('.flow-node.shot .node-preview', 'backgroundColor'), 'rgb(255, 255, 255)')
  assert.equal(await css('.video-composer', 'backgroundColor'), 'rgb(255, 255, 255)')
  assert.equal(await css('.prompt-editor', 'color'), 'rgb(48, 49, 54)')
  await page.locator('.reference-chip').first().hover()
  await page.locator('.reference-hover-preview').waitFor()
  assert.equal(await css('.reference-hover-preview', 'color'), 'rgb(48, 49, 54)')
  await page.getByRole('textbox', { name: '视频画面描述' }).hover()
  await page.getByRole('button', { name: '视频生成设置', exact: true }).click()
  assert.equal(await css('.generation-settings', 'backgroundColor'), 'rgb(255, 255, 255)')
  await page.screenshot({ path: 'docs/_shots/day-canvas.png' })
  await page.getByRole('button', { name: '关闭视频生成设置' }).click()
  await page.getByRole('textbox', { name: '视频画面描述' }).press('Control+End')
  await page.getByRole('textbox', { name: '视频画面描述' }).pressSequentially(' @')
  await page.locator('.mention-menu').waitFor()
  assert.equal(await css('.mention-menu', 'backgroundColor'), 'rgb(255, 255, 255)')
  await page.getByRole('textbox', { name: '视频画面描述' }).press('Escape')
  await page.getByRole('button', { name: '更多画布操作', exact: true }).click()
  await page.getByRole('button', { name: '剧本建镜', exact: true }).click()
  await page.locator('.studio-dialog').waitFor()
  assert.equal(await css('.studio-dialog', 'color'), 'rgb(48, 49, 54)')
  await page.getByRole('button', { name: '关闭对话框', exact: true }).click()
  await waitSaved()
  await page.reload(); await page.locator('.flow-node').first().waitFor()
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light', 'day mode persists on reload')
  await selectCreation(0)
  await page.screenshot({ path: 'docs/_shots/day-composer.png' })
  await page.locator('.settings-button').click()
  await page.locator('.settings-dialog').waitFor()
  assert.equal(await css('.settings-dialog', 'backgroundColor'), 'rgb(255, 255, 255)')
  assert.equal(await css('.settings-dialog', 'color'), 'rgb(48, 49, 54)')
  await page.screenshot({ path: 'docs/_shots/day-services.png' })
  await page.locator('.settings-dialog .icon-button').click()
  await page.goto(`${url}/?browser-test=theme-materials#project=${taskId}&view=studio`)
  await page.locator('.mcard').first().waitFor()
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'light')
  await page.locator('.mcard').first().getByRole('button', { name: '提示词', exact: true }).click()
  await page.getByRole('dialog', { name: '提示词', exact: true }).waitFor()
  await page.screenshot({ path: 'docs/_shots/day-material-dialog.png' })
  await page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click()
  await page.screenshot({ path: 'docs/_shots/day-materials.png' })
  await page.goto(`${url}/?browser-test=theme-home`)
  await page.getByRole('heading', { name: '你的下一部作品，从这里开始。' }).waitFor()
  await page.waitForTimeout(450)
  await page.screenshot({ path: 'docs/_shots/day-home.png' })
  await openCanvas(); await selectCreation(0)
  await page.setViewportSize({ width: 390, height: 844 })
  if (await page.locator('.sequence-toggle').getAttribute('aria-expanded') === 'true') await page.locator('.sequence-toggle').click()
  await assertNoOverflow()
  await page.screenshot({ path: 'docs/_shots/day-mobile.png' })
  await page.locator('.navigation-toggle').click()
  await page.getByRole('button', { name: '切换夜间模式', exact: true }).click()
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark')
  await page.locator('.navigation-backdrop').click({ position: { x: 380, y: 10 } })
  await page.reload(); await page.locator('.flow-node').first().waitFor()
  assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark', 'night mode also persists on reload')
  assert.equal(await css('.flow-board', 'backgroundColor'), 'rgb(17, 18, 22)')
  assert.deepEqual(errors, [])
  assert.deepEqual(unexpected, [])
  // Uploaded footage gets a dedicated reference node and survives a canvas reload.
  await page.setViewportSize({ width: 1440, height: 1000 })
  cfg.video_workflow = 'ref2va'
  graph = emptyWorkflow()
  const cleanShot = makeShot(430, 70)
  const cleanImage = makeNode('material', 30, 70, { title: '山海晨光', materialKind: 'scene', materialName: '山海晨光', materialFile: 'morning.webp' })
  graph.nodes = [cleanImage, cleanShot]
  graph.edges = [{ id: 'image-reference', source: cleanImage.id, target: cleanShot.id }]
  graph.viewport = { x: 150, y: 130, zoom: 1 }
  await page.evaluate(taskId => localStorage.removeItem(`frameflow.workflow.${taskId}`), taskId)
  await page.reload(); await page.locator('.flow-node').first().waitFor()
  assert.equal(await page.locator('.node-footer').count(), 0, 'cards do not repeat titles and explanatory copy')
  await page.waitForFunction(() => document.querySelector('.flow-node.material .node-meta')?.textContent.includes('×'))
  await page.screenshot({ path: 'docs/_shots/minimal-canvas-dark.png' })
  await selectCreation(0)
  assert.ok(await page.getByRole('button', { name: '上传视频', exact: true }).isVisible())
  await page.locator('input[type=file][accept=".mp4,.mov,.webm,.mkv,.m4v"]').setInputFiles({ name: '参考视频.mp4', mimeType: 'video/mp4', buffer: videoFixture })
  await page.locator('.flow-node.footage video').waitFor()
  await waitSaved()
  const footage = graph.nodes.find(n => n.type === 'footage')
  assert.equal(footage.data.versions[0].file, 'upload_012345abcdef.mp4')
  assert.equal(graph.edges.find(e => e.source === footage.id).usage, 'reference')
  assert.equal(await page.locator('.sequence-shot').count(), 1, 'reference videos are not export or generation shots')
  await page.getByRole('textbox', { name: '视频画面描述' }).fill('借鉴来源视频中的动作，镜头缓慢推进。')
  await page.getByRole('button', { name: '生成视频', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.node-state i.succeeded'))
  assert.equal(submissions.at(-1).video_sources[0].file, 'upload_012345abcdef.mp4')
  assert.equal(submissions.at(-1).video_sources[0].usage, 'reference')
  await page.getByLabel('参考视频 来源用途', { exact: true }).selectOption('continue')
  const continuationSubmission = page.waitForResponse(response => response.url().endsWith('/segment/video') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '生成视频', exact: true }).click()
  await continuationSubmission
  await page.waitForFunction(() => document.querySelector('.node-state i.succeeded') && !document.querySelector('.node-state i:is(.running, .queued, .composing)'))
  assert.equal(submissions.at(-1).video_sources[0].usage, 'continue')
  await waitSaved(); await page.reload(); await page.locator('.flow-node.footage video').waitFor()
  assert.equal(graph.nodes.filter(n => n.type === 'footage').length, 1)
  await page.getByRole('button', { name: '切换白天模式', exact: true }).click()
  await page.getByRole('button', { name: '关闭视频输入框', exact: true }).click()
  await page.getByRole('button', { name: '显示全部节点', exact: true }).click()
  await page.mouse.move(1300, 70)
  await page.screenshot({ path: 'docs/_shots/minimal-canvas-light.png' })
  await selectCreation(0)
  await page.screenshot({ path: 'docs/_shots/uploaded-video-reference.png' })

  // Marquee, groups and bulk references use real pointer events with no model calls.
  await page.goto(`${url}/?browser-test=home`)
  await page.getByRole('heading', { name: '你的下一部作品，从这里开始。' }).waitFor()
  graph = emptyWorkflow()
  const groupedScene = makeNode('material', 80, 80, { title: '山海晨光', materialKind: 'scene', materialName: '山海晨光', materialFile: 'morning.webp' })
  const groupedProp = makeNode('material', 470, 80, { title: '未寄出的信', materialKind: 'prop', materialName: '未寄出的信', materialFile: 'letter.webp' })
  const groupedVideo = makeNode('footage', 80, 360, { title: '动作参考', status: 'succeeded', versions: [structuredClone(footage.data.versions[0])] })
  const groupTarget = makeShot(1000, 220)
  groupTarget.data.status = 'succeeded'
  groupTarget.data.versions = [{ id: 'completed-target', status: 'succeeded', file: 'completed-target.mp4', url: `/files/${taskId}/segments/completed-target.mp4` }]
  graph.nodes = [groupedScene, groupedProp, groupedVideo, groupTarget]
  await page.evaluate(key => localStorage.removeItem(key), `frameflow.workflow.${taskId}`)
  await openCanvas(); await waitSaved()
  await page.getByRole('button', { name: '显示全部节点', exact: true }).click(); await waitSaved()
  await page.mouse.click((await emptyCanvasPoint()).x, (await emptyCanvasPoint()).y)
  const sourceIds = [groupedScene.id, groupedProp.id, groupedVideo.id]
  const sourceCards = page.locator(sourceIds.map(id => `[data-node-id="${id}"]`).join(','))
  const sourceRect = await sourceCards.evaluateAll(cards => {
    const rects = cards.map(card => card.getBoundingClientRect())
    return { x: Math.min(...rects.map(r => r.left)) - 12, y: Math.min(...rects.map(r => r.top)) - 12, right: Math.max(...rects.map(r => r.right)) + 12, bottom: Math.max(...rects.map(r => r.bottom)) + 12 }
  })
  const marqueeViewport = structuredClone(graph.viewport)
  await page.mouse.move(sourceRect.right, sourceRect.bottom); await page.mouse.down()
  await page.mouse.move(sourceRect.x, sourceRect.y, { steps: 10 })
  assert.equal(await page.locator('.selection-marquee').count(), 1)
  await page.mouse.up()
  assert.equal(await page.locator('.flow-node.selected').count(), 3)
  assert.equal(await page.locator('.video-composer').count(), 0)
  assert.equal(await page.locator('.flow-inspector').count(), 0)
  assert.deepEqual(graph.viewport, marqueeViewport, 'blank left drag selects without moving the camera')
  const positions = structuredClone(graph.nodes)
  const sourcePreview = await sourceCards.first().locator('.node-preview').boundingBox()
  await page.mouse.move(sourcePreview.x + 70, sourcePreview.y + 60); await page.mouse.down()
  await page.mouse.move(sourcePreview.x + 110, sourcePreview.y + 85, { steps: 5 }); await page.mouse.up(); await waitSaved()
  for (const id of sourceIds) {
    const n = graph.nodes.find(n => n.id === id), old = positions.find(n => n.id === id)
    assert.ok(Math.abs(n.x - old.x - 40 / graph.viewport.zoom) < 1)
    assert.ok(Math.abs(n.y - old.y - 25 / graph.viewport.zoom) < 1)
  }
  assert.deepEqual(graph.nodes.find(n => n.id === groupTarget.id), positions.find(n => n.id === groupTarget.id))
  await page.getByRole('button', { name: '打组', exact: true }).click(); await waitSaved()
  await page.getByRole('textbox', { name: '素材组名称', exact: true }).fill('场景与动作参考')
  await page.getByRole('textbox', { name: '素材组名称', exact: true }).press('Enter')
  await page.getByRole('button', { name: '一起连接', exact: true }).focus(); await waitSaved()
  const groupId = graph.nodes[0].data.groupId
  assert.ok(sourceIds.every(id => graph.nodes.find(n => n.id === id).data.groupId === groupId))
  await page.reload(); await page.locator('.canvas-group').waitFor()
  await sourceCards.first().locator('.node-preview').click({ position: { x: 60, y: 60 } })
  assert.equal(await page.locator('.flow-node.selected').count(), 3, 'clicking a grouped material selects the whole saved group')
  assert.equal(await page.getByRole('textbox', { name: '素材组名称', exact: true }).inputValue(), '场景与动作参考')
  const frame = await page.locator('.canvas-group').boundingBox()
  await waitSaved(); const groupBefore = structuredClone(graph.nodes)
  await page.mouse.move(frame.x + 9, frame.y + frame.height / 2); await page.mouse.down()
  await page.mouse.move(frame.x + 29, frame.y + frame.height / 2 + 10, { steps: 5 }); await page.mouse.up(); await waitSaved()
  assert.ok(sourceIds.every(id => graph.nodes.find(n => n.id === id).x > groupBefore.find(n => n.id === id).x))
  await page.getByRole('button', { name: '平移工具', exact: true }).click()
  await page.getByRole('button', { name: '一起连接', exact: true }).click()
  assert.equal(await page.locator('.loose-edge').count(), 3)
  const targetPreview = page.locator(`[data-node-id="${groupTarget.id}"] .node-preview`)
  await targetPreview.hover()
  assert.ok(await page.locator(`[data-node-id="${groupTarget.id}"].link-hovered`).count())
  const targetBeforeConnection = structuredClone(graph.nodes.find(n => n.id === groupTarget.id))
  const targetFrame = await targetPreview.boundingBox()
  await page.mouse.click(targetFrame.x + targetFrame.width / 2, targetFrame.y + targetFrame.height - 12); await waitSaved()
  assert.equal(graph.edges.length, 3)
  assert.equal(graph.edges.find(e => e.source === groupedVideo.id).usage, 'reference')
  assert.deepEqual(graph.nodes.find(n => n.id === groupTarget.id), targetBeforeConnection, 'connecting anywhere in a completed video frame never drags it, changes its result or activates native playback controls')
  assert.ok(await page.locator(`[data-node-id="${groupTarget.id}"] video`).evaluate(video => video.paused), 'linking over the video controls does not start playback')
  await page.getByRole('button', { name: '选择工具', exact: true }).click()
  assert.equal(await page.locator('.video-source').count(), 1)
  await page.getByRole('button', { name: '关闭视频输入框', exact: true }).click()
  await page.getByRole('button', { name: '显示全部节点', exact: true }).click(); await waitSaved()
  await sourceCards.first().locator('.node-preview').click({ position: { x: 60, y: 60 } })
  await page.getByRole('button', { name: '创建副本', exact: true }).click(); await waitSaved()
  assert.equal(graph.nodes.length, 7)
  assert.equal(new Set(graph.nodes.filter(n => n.data.groupId).map(n => n.data.groupId)).size, 2)
  await page.getByRole('button', { name: '一起连接', exact: true }).click()
  await page.locator(`[data-node-id="${groupTarget.id}"] .node-preview`).click({ position: { x: 150, y: 80 } })
  await page.getByText('一镜只能使用一个场景，请移除多余场景', { exact: true }).waitFor()
  assert.equal(graph.edges.length, 3, 'invalid bulk references are rejected without partial connections')
  await page.getByRole('button', { name: '关闭通知：一镜只能使用一个场景，请移除多余场景', exact: true }).click()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '撤销', exact: true }).click(); await waitSaved()
  assert.equal(graph.nodes.length, 4)
  await sourceCards.first().locator('.node-preview').click({ position: { x: 60, y: 60 }, modifiers: ['Alt'] })
  assert.equal(await page.locator('.flow-node.selected').count(), 1, 'Alt allows editing one member')
  await sourceCards.nth(1).locator('.node-preview').click({ position: { x: 60, y: 60 }, modifiers: ['Shift'] })
  assert.equal(await page.locator('.flow-node.selected').count(), 2)
  await sourceCards.nth(1).locator('.node-preview').click({ position: { x: 60, y: 60 }, modifiers: ['Shift'] })
  assert.equal(await page.locator('.flow-node.selected').count(), 1, 'Shift toggles an individual member')
  await sourceCards.nth(1).locator('.node-preview').click({ position: { x: 60, y: 60 } })
  await page.getByRole('button', { name: '解组', exact: true }).click(); await waitSaved()
  assert.equal(await page.locator('.canvas-group').count(), 0)
  await page.getByRole('button', { name: '撤销', exact: true }).click(); await waitSaved()
  await sourceCards.first().locator('.node-preview').click({ position: { x: 60, y: 60 } })
  assert.equal(await css('.canvas-group', 'backgroundColor'), 'rgb(233, 233, 235)')
  assert.equal(await page.locator('.edge-flow').count(), 3)
  const flowOffset = await css('.edge-flow', 'strokeDashoffset')
  await page.waitForTimeout(160)
  assert.notEqual(await css('.edge-flow', 'strokeDashoffset'), flowOffset, 'selected reference lines visibly flow')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  assert.equal(await css('.edge-flow', 'display'), 'none', 'reduced-motion preference keeps reference lines static')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  const deselectPoint = await emptyCanvasPoint()
  await page.mouse.click(deselectPoint.x, deselectPoint.y)
  assert.equal(await page.locator('.edge-flow').count(), 0, 'unselected relations stay static')
  await sourceCards.first().locator('.node-preview').click({ position: { x: 60, y: 60 }, modifiers: ['Alt'] })
  assert.equal(await page.locator('.edge-flow').count(), 1, 'only the selected material relation flows')
  await page.waitForFunction(() => [...document.querySelectorAll('.flow-edges g:not(.highlighted) .edge-line')].every(path => getComputedStyle(path).opacity === '0.35'))
  assert.equal(await css('.flow-edges g:not(.highlighted) .edge-line', 'opacity'), '0.35')
  await sourceCards.nth(1).locator('.node-preview').click({ position: { x: 60, y: 60 } })
  await waitSaved()
  await page.mouse.move(1300, 70)
  await page.screenshot({ path: 'docs/_shots/grouped-canvas-light.png' })
  await page.getByRole('button', { name: '切换夜间模式', exact: true }).click()
  await page.waitForTimeout(200)
  await page.mouse.move(1300, 70)
  await page.screenshot({ path: 'docs/_shots/grouped-canvas-dark.png' })
  const spacePoint = await emptyCanvasPoint(); const viewBeforeSpace = structuredClone(graph.viewport)
  await page.locator('.workflow-editor').focus(); await page.keyboard.down('Space')
  await page.mouse.move(spacePoint.x, spacePoint.y); await page.mouse.down()
  await page.mouse.move(spacePoint.x + 25, spacePoint.y + 20, { steps: 5 }); await page.mouse.up(); await page.keyboard.up('Space'); await waitSaved()
  assert.equal(graph.viewport.x, viewBeforeSpace.x + 25)
  assert.equal(graph.viewport.y, viewBeforeSpace.y + 20)
  await page.setViewportSize({ width: 390, height: 844 })
  await assertNoOverflow()
  assert.deepEqual(errors, [])
  assert.deepEqual(unexpected, [])
  console.log('PASS: creation cards, migration, composer settings, serial generation, candidate playback, queue/save protection, export, imports and mobile layout. Material editing, prompt/AI/history/preview/assistant dialogs and generation records passed. Marquee and additive selection, group dragging/naming/persistence/copy/ungroup/undo, atomic bulk connections by video frame, native-control protection, target hover, selection-only flow and reduced motion, Space/middle panning passed. Neutral day/night colors, reload persistence and the mobile theme switch passed. No live model calls.')
} catch (error) { console.error('UI state:', await page.locator('body').innerText(), 'Errors:', errors, 'Unexpected routes:', unexpected); await page.screenshot({ path: 'docs/_shots/studio-test-failure.png' }); throw error }
finally { await browser.close() }
